server:
  port: 7800
spring:
  application:
    name: exam
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/exam
    username: root
    password: mysql
#mybatis
mybatis:
  typeAliasesPackage: com.example.exam.model
  mapperLocations: classpath:mapper/*.xml